import { logError } from './log';
import { discordTimestamp } from './perthTime';
import type { CommitteeEntry } from '../database/models/CommitteeModel';
import type { EventEntry } from '../database/models/EventModel';

/**
 * Club data tools for the Marv persona (UWA AI Club mascot).
 *
 * First-party read-only tools, following the get_music_guide skill pattern:
 * the model calls them and gets plain text back. Results are TRUSTED (not wrapped
 * in <<MCP_TOOL_RESULT>> markers) because they come from our own DB and repo, not
 * from the open web.
 *
 * - recall_constitution → data/skills/constitution.md (generated by
 *   `bun run fetch:constitution` from the club's constitution.tex)
 * - list_committee      → the Committee table for the calling guild
 * - list_events         → the Event table for the calling guild
 *
 * The hand-maintained markdown sheets (club links, UWA key dates, student perks,
 * FAQ) are a separate family — see utils/referenceSheets.ts.
 */

export const CONSTITUTION_TOOL_NAME = 'recall_constitution';
export const COMMITTEE_TOOL_NAME = 'list_committee';
export const EVENTS_TOOL_NAME = 'list_events';

export const CLUB_TOOL_NAMES = [
  CONSTITUTION_TOOL_NAME,
  COMMITTEE_TOOL_NAME,
  EVENTS_TOOL_NAME,
];

const CONSTITUTION_PATH = `${import.meta.dir}/../data/skills/constitution.md`;

// Perth time helpers live in ./perthTime so utils/referenceSheets.ts can use them
// without importing this module (which would be a cycle). Re-exported here
// because commands and tests already import them from clubInfo.
export {
  PERTH_UTC_OFFSET_MINUTES,
  TIME_FORMAT_HINT,
  parsePerthDateTime,
  perthDateString,
  perthYear,
  formatPerthDateTime,
  discordTimestamp,
} from './perthTime';

const EVENTS_DEFAULT_LIMIT = 15;
const EVENTS_MAX_LIMIT = 50;

const CONSTITUTION_DESCRIPTION = 'Returns the full text of the UWA AI Club constitution (governance rules, '
  + 'membership, committee roles and duties, meetings, quorum, elections, finances). Call this BEFORE answering '
  + 'any question about club rules, procedures, or how the club is governed — quote it rather than guessing.';

const COMMITTEE_DESCRIPTION = 'Returns the current UWA AI Club committee roster for this server: each role title, '
  + 'the person holding it, and their Discord mention. Call this whenever someone asks who holds a role, who to '
  + 'contact about something, or who is on committee. Use the <@id> mentions verbatim when naming people.';

const EVENTS_DESCRIPTION = 'Returns the club\'s scheduled events (name, time, location, description). Call this '
  + 'whenever someone asks what is coming up, when the next event is, or about a specific event. Times come back '
  + 'as Discord timestamps like <t:1234567890:F> — reproduce them verbatim so each reader sees their own timezone.';

export interface ClubContext {
  /** Shared Database instance (db.committee, db.event). */
  db: any;
  /** Guild the message came from — all club data is scoped per guild. */
  guildId: string;
}

// ---------------------------------------------------------------------------
// Formatting (shared by the slash commands and the AI tools)
// ---------------------------------------------------------------------------

export function formatCommitteeRoster(entries: CommitteeEntry[]): string {
  if (entries.length === 0) return 'No committee members are registered for this server yet.';

  const render = (entry: CommitteeEntry): string => {
    const name = entry.displayName ? ` — ${entry.displayName}` : '';
    return `- ${entry.title}: <@${entry.userId}>${name}`;
  };

  const execs = entries.filter((entry) => entry.isExecutive);
  const others = entries.filter((entry) => !entry.isExecutive);

  const sections: string[] = [];
  if (execs.length > 0) sections.push(`**Executive**\n${execs.map(render).join('\n')}`);
  if (others.length > 0) sections.push(`**Non-Executive**\n${others.map(render).join('\n')}`);
  return sections.join('\n\n');
}

export function formatEventList(events: EventEntry[]): string {
  if (events.length === 0) return 'No events are scheduled.';

  return events.map((event) => {
    const parts = [`**${event.name}** (id ${event.id})`];
    parts.push(`  When: ${discordTimestamp(event.startsAt)} (${discordTimestamp(event.startsAt, 'R')})`);
    if (event.endsAt) parts.push(`  Until: ${discordTimestamp(event.endsAt)}`);
    if (event.location) parts.push(`  Where: ${event.location}`);
    if (event.url) parts.push(`  Link: ${event.url}`);
    if (event.description) parts.push(`  ${event.description}`);
    return parts.join('\n');
  }).join('\n\n');
}

// ---------------------------------------------------------------------------
// Tool definitions
// ---------------------------------------------------------------------------

export function clubToolDefs(): any[] {
  return [
    {
      type: 'function',
      function: {
        name: CONSTITUTION_TOOL_NAME,
        description: CONSTITUTION_DESCRIPTION,
        parameters: { type: 'object', properties: {} },
      },
    },
    {
      type: 'function',
      function: {
        name: COMMITTEE_TOOL_NAME,
        description: COMMITTEE_DESCRIPTION,
        parameters: {
          type: 'object',
          properties: {
            query: {
              type: 'string',
              description: 'Optional case-insensitive filter on role title or name (e.g. "treasurer").',
            },
          },
        },
      },
    },
    {
      type: 'function',
      function: {
        name: EVENTS_TOOL_NAME,
        description: EVENTS_DESCRIPTION,
        parameters: {
          type: 'object',
          properties: {
            include_past: {
              type: 'boolean',
              description: 'Include events that have already finished. Defaults to false.',
            },
            limit: {
              type: 'integer',
              description: `Maximum events to return (1-${EVENTS_MAX_LIMIT}). Defaults to ${EVENTS_DEFAULT_LIMIT}.`,
            },
          },
        },
      },
    },
  ];
}

/** System-prompt note advertising the club tools (kept tiny — the detail is in the tool descriptions). */
export function buildClubNote(club?: ClubContext): string {
  if (!club) return '';
  return '\n\nYou have live access to UWA AI Club data. Call '
    + `${COMMITTEE_TOOL_NAME} for who holds which committee role, ${EVENTS_TOOL_NAME} for what is coming up, and `
    + `${CONSTITUTION_TOOL_NAME} for the club constitution. These are the source of truth — call the relevant tool `
    + 'instead of guessing or relying on anything in this prompt, and say so plainly if the data comes back empty.';
}

// ---------------------------------------------------------------------------
// Handlers
// ---------------------------------------------------------------------------

let cachedConstitution: string | null = null;

/** The constitution text served to the model by recall_constitution. */
export async function getConstitution(): Promise<string> {
  if (cachedConstitution !== null) return cachedConstitution;
  try {
    cachedConstitution = await Bun.file(CONSTITUTION_PATH).text();
  } catch (err) {
    logError('[club] failed to read constitution:', err);
    return 'Error: the club constitution is unavailable right now. Tell the user you cannot look it up '
      + 'and point them at https://github.com/UWA-AI-Club/constitution instead.';
  }
  return cachedConstitution;
}

export async function runListCommittee(club: ClubContext, args: { query?: string } = {}): Promise<string> {
  try {
    const entries: CommitteeEntry[] = await club.db.committee.listByServer(club.guildId);
    const query = typeof args.query === 'string' ? args.query.trim().toLowerCase() : '';
    const filtered = query
      ? entries.filter((entry) => entry.title.toLowerCase().includes(query)
        || (entry.displayName ?? '').toLowerCase().includes(query))
      : entries;

    if (query && filtered.length === 0) {
      return `No committee role or member matches "${args.query}". Full roster:\n\n${formatCommitteeRoster(entries)}`;
    }
    return formatCommitteeRoster(filtered);
  } catch (err) {
    logError('[club] list_committee failed:', err);
    return 'Error: the committee roster could not be read right now.';
  }
}

export async function runListEvents(
  club: ClubContext,
  args: { include_past?: boolean; limit?: number } = {},
): Promise<string> {
  try {
    const rawLimit = Number(args.limit);
    const limit = Number.isFinite(rawLimit)
      ? Math.min(Math.max(Math.trunc(rawLimit), 1), EVENTS_MAX_LIMIT)
      : EVENTS_DEFAULT_LIMIT;

    const events: EventEntry[] = args.include_past === true
      ? await club.db.event.listAll(club.guildId, limit)
      : await club.db.event.listUpcoming(club.guildId, limit);

    if (events.length === 0) {
      return args.include_past === true
        ? 'No events are recorded for this server.'
        : 'No upcoming events are scheduled. (Past events exist only if include_past is set.)';
    }
    return formatEventList(events);
  } catch (err) {
    logError('[club] list_events failed:', err);
    return 'Error: the event list could not be read right now.';
  }
}
