/**
 * Downloads the UWA AI Club constitution (LaTeX) and converts it to the markdown
 * that Marv serves through the recall_constitution tool (utils/clubInfo.ts).
 *
 * Usage: bun scripts/fetch-constitution.ts
 * The generated data/skills/constitution.md IS committed, so a fresh clone works
 * without running this. Re-run it whenever the constitution repo changes.
 */

import { latexToMarkdown } from '../utils/latexToMarkdown';

const SOURCE_URL = 'https://raw.githubusercontent.com/UWA-AI-Club/constitution/main/constitution.tex';
const DEST = `${import.meta.dir}/../data/skills/constitution.md`;

async function main(): Promise<void> {
  console.log(`Downloading ${SOURCE_URL} ...`);
  const res = await fetch(SOURCE_URL);
  if (!res.ok) throw new Error(`Download failed: HTTP ${res.status}`);
  const tex = await res.text();

  const body = latexToMarkdown(tex);
  if (body.length < 1000) {
    throw new Error(`Conversion produced only ${body.length} characters — the source format probably changed.`);
  }

  const header = [
    '# UWA Artificial Intelligence Club — Constitution',
    '',
    `> Generated by \`bun run fetch:constitution\` from ${SOURCE_URL}`,
    `> on ${new Date().toISOString().slice(0, 10)}. Do not edit by hand — edit the source repo and re-run.`,
    '',
  ].join('\n');

  await Bun.write(DEST, `${header}\n${body}\n`);
  console.log(`Wrote ${(body.length / 1000).toFixed(1)}k characters to ${DEST}`);
}

main().catch((err) => {
  console.error(err instanceof Error ? err.message : err);
  process.exitCode = 1;
});
